---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_new_nsxman.yml
  tasks:
  - name: NSX Manager SSO Registration
    nsxSsoRegistration:
      state: present
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      sso_lookupservice_url: 'https://172.17.100.60:7444/lookupservice/sdk'
      sso_admin_username: 'administrator@vsphere.local'
      sso_admin_password: 'vmware'
      sso_certthumbprint: '33:80:F0:58:DB:D4:59:A2:46:14:83:14:2C:48:C3:29:70:25:BE:31'
    register: register_to_sso

#  - debug: var=register_to_sso