---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_old_nsxman.yml
  tasks:
  - name: logicalSwitch Operation
    logicalSwitch:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: absent
      transportzone: "TZ"
      name: "TestLS"
      controlplanemode: "HYBRID_MODE"
      description: "My Great Logical Switch"
    register: create_logical_switch

  #- debug: var=create_logical_switch
